"""add retry fields

Revision ID: b65e0563d7ab
Revises: b8afdd9e12d6
Create Date: 2025-07-13 19:20:20.680965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b65e0563d7ab'
down_revision: Union[str, None] = 'b8afdd9e12d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('max_retries', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'max_retries')
    op.drop_column('jobs', 'retry_count')
    # ### end Alembic commands ###
